name: Verification Suite
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  Verify:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    container:
      options: --security-opt seccomp=unconfined

    steps:
      - name: Checkout autoschematic
        uses: actions/checkout@v4
        with:
          path: autoschematic

      - name: Checkout verification suite
        uses: actions/checkout@v4
        with:
          repository: autoschematic-sh/autoschematic-verification-suite
          path: autoschematic-verification-suite
          token: ${{ secrets.GITHUB_TOKEN }}
          
      # - name: Install build-essential
      #   run: |
      #     sudo apt update
      #     sudo apt install build-essential
          
      - name: Install protobuf
        run: apt-get update && apt-get install -y protobuf-compiler build-essential
      - name: Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        # with:
        #   components: clippy,rustfmt

      # - name: Cache Cargo
      #   uses: Swatinem/rust-cache@v2
      #   with:
      #     workspaces: |
      #       autoschematic
      #       autoschematic-verification-suite

      - name: Install Autoschematic
        working-directory: autoschematic
        run: |
          cargo install --path autoschematic

      - name: Install Scoreboard Connector
        working-directory: autoschematic-verification-suite
        run: |
          cargo install --path autoschematic-connector-scoreboard-dummy


      # # Make the suite build against THIS checkout instead of crates.io/git
      # - name: Patch deps to local paths
      #   working-directory: autoschematic-verification-suite
      #   run: |
      #     mkdir -p .cargo
      #     cat > .cargo/config.toml <<'EOF'
      #     [patch.crates-io]
      #     autoschematic-core = { path = "../autoschematic/autoschematic-core" }
      #     EOF

      - name: Run verification suite
        working-directory: autoschematic-verification-suite
        run: |
          bash run_suite.sh

      # - name: Upload logs (always)
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: verification-logs
      #     path: |
      #       verification/target/**/*.log
      #       verification/**/*.junit.xml
      #       verification/**/*.json
      #     if-no-files-found: ignore
